---

- name: Install rsync
  package:
    name: rsync
    state: present

- name: Update rsyncd.conf
  template:
    src: rsyncd.conf.j2
    dest: /etc/rsyncd.conf
    mode: '0444'
    owner: root
    group: root
  when: rsync_modules is defined

- name: Enable rsyncd
  service:
    name: rsyncd
    enabled: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'
