---
- name: Converge
  hosts: all
  tasks:
    - name: "Include uclalib_role_rsyncd"
      include_role:
        name: "uclalib_role_rsyncd"

  vars:
    # referenced by assert: in verify.yml
    modules:
      one:
        path: /tmp
      two:
        comment: Second
